app/config/routes.rb
App::Application.routes.draw do

  resources :todos
  resources :users

  match '/(:action)' => 'main#index'

end

app/app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :auth
  helper_method :logged_in?
  helper_method :username
  

  def logged_in?
    defined?(@user)
  end

  def username
    logged_in? ? @user.name : ""
  end

  private
  
  def auth
    if session[:user_id]
      @user = User.find(session[:user_id]) if session[:user_id]
    end
  end
end

app/app/controllers/main_controller.rb
class MainController < ApplicationController
  REDIS = Redis.new

  def signin
    if request.post?
      user = User.where(:email => params[:email]).first

      if user
        session[:user_id] = user.id
        redirect_to '/'
      end
    end
  end

  def index
    if logged_in?
      @todo = Todo.new
      render :index2
    end
  end

  def signout
    session[:user_id] = nil
    redirect_to '/'
  end

  def health
    render :text => 'healthy'
  end
end

app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(params[:todo])
    @todo.user_id = @user.id

    respond_to do |format|
      if @todo.save
        format.html { redirect_to '/', notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :ok }
    end
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/main_helper.rb
module MainHelper
end

app/app/helpers/todos_helper.rb
module TodosHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %title Todo List
    = stylesheet_link_tag "application"
    %style
      :sass
        body
          margin-top: 50px
  %body
    .topbar
      .fill
        .container
          %a{:class => "brand", :href => "/"} Todo List
          %ul.nav
            %li
              %a(href = "/") Home
            %li
              - if logged_in?
                = link_to "(#{username}) Sign Out", "/signout"
              - else
                = link_to "Sign In", "/signin"

    .container
      .content
        = yield
          
      %footer
        <p>&copy; Factual 2011</p>

app/app/views/main/index.html.haml
%h1 Todos

%ul
  %li= link_to "Sign Up", new_user_path
  %li= link_to "Sign In", "/signin"

app/app/views/main/index2.html.haml
#{@user.name}
%ol
  - @user.todos.each do |t|
    %li= t.content

= render '/todos/form'

app/app/views/main/signin.html.haml
%form{ :method => 'post' }
  %label Email
  %input{ :name => 'email' }
  %br/
  %input{ :type => 'submit', :value => 'Sign In' }

app/app/views/todos/_form.html.haml
= form_for @todo do |f|
  -if @todo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
      %ul
        - @todo.errors.full_messages.each do |msg|
          %li= msg
    = f.hidden_field :user_id
  .field
    = f.label :todo
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo
\|
= link_to 'Back', todos_path

app/app/views/todos/index.html.haml
%h1 Listing todos

%table
  %tr
    %th Content
    %th User
    %th
    %th
    %th

  - @todos.each do |todo|
    %tr
      %td= todo.content
      %td= todo.user_id
      %td= link_to 'Show', todo
      %td= link_to 'Edit', edit_todo_path(todo)
      %td= link_to 'Destroy', todo, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Todo', new_todo_path

app/app/views/todos/new.html.haml
%h1 New todo

= render 'form'

= link_to 'Back', todos_path

app/app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @todo.content
%p
  %b User:
  = @todo.user_id

= link_to 'Edit', edit_todo_path(@todo)
\|
= link_to 'Back', todos_path

app/app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path